name: Flutter

on:
  pull_request:
    types: [closed]

jobs:
  post_merge_action:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
      
      - name: Install dependencies
        run: flutter pub get